### ISSUE TITLE
Serving geospatial data for the frontend

### ISSUE THREAD

**Issue by nofurtherinformation** [chihacknight/chicago-elections-archive#5]
Currently, the geospatial map data is deployed on a tile server hosted on linode. This is a good and scaleable solution, especially if this project were to scale up to national election archives, for instance. 

However, there are some simpler and more maintainable solutions that could simplify data workflows:

Options include
- Traditional tile server (backend MBTiles server, file hierarchy pre-baked) or service (maptiler)
- PMTiles single static file tiles
- Geospatial data directly (geojson)

My instinct here is to start with simple geojsons. From a quick first look, Ward Precincts can be compressed to around 500kb with reasonable simplification and gzip. Geometric simplification is appropriate here because this is primarily for visualization, not geospatial data science or geoprocessing, and we can point back to the source files for analysts who need the real deal.

**Comment by derekeder** [comment]
agreed, lets start with geojson and see if that meets our needs.

**Comment by nofurtherinformation** [comment]
I'll take a first pass at this tomorrow and plan to use commodity storage (likely Cloudflare R2 for simplicity)

**Comment by nofurtherinformation** [comment]
Closed by #9
